model_config:
  target: models.lrm.models.lrm_mesh.PRM
  params:
    encoder_feat_dim: 768
    encoder_freeze: false
    encoder_model_name: facebook/dino-vitb16
    transformer_dim: 1024
    transformer_layers: 16
    transformer_heads: 16
    triplane_low_res: 32
    triplane_high_res: 48
    triplane_dim: 80
    rendering_samples_per_ray: 128
    grid_res: 96
    grid_scale: 2.1


infer_config:
  unet_path: ckpts/diffusion_pytorch_model.bin
  model_path: ckpts/final_ckpt.ckpt
  texture_resolution: 1536
  render_resolution: 384